"""Stress the SQLite data layer with generated semester-sized task data.

Run from the project root:

    python scripts/stress_db.py
    python scripts/stress_db.py --tasks 10000 --queries 5000 --mutations 2000

The script uses a temporary database by default and does not touch
``data/tasks.db``.
"""
from __future__ import annotations

import argparse
import random
import statistics
import sys
import time
from collections.abc import Callable
from datetime import date, timedelta
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Any

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_PROJECT_ROOT))

from database import db  # noqa: E402
from database.models import Module, TASK_TYPES, Task  # noqa: E402

_RNG_SEED: int = 20260508
_STRESS_CHAT_ID: int = 999_999
_MODULE_CODES: tuple[str, ...] = (
    "CS2040",
    "CS2030",
    "MH2100",
    "MH2200",
    "MH2500",
    "CC0001",
    "CZ3005",
    "BU8601",
)
_TIME_CHOICES: tuple[str | None, ...] = (
    None,
    "09:00",
    "12:00",
    "17:00",
    "23:59",
)


def _measure_ms(fn: Callable[..., Any], *args: object) -> float:
    """Run ``fn`` once and return elapsed time in milliseconds."""
    started = time.perf_counter()
    fn(*args)
    return (time.perf_counter() - started) * 1000


def _p95(values: list[float]) -> float:
    """Return a practical p95 for a non-empty list of timings."""
    if len(values) < 20:
        return max(values) if values else 0.0
    return statistics.quantiles(values, n=20)[18]


def _generate_task(index: int, rng: random.Random, semester_start: date) -> Task:
    """Build a deterministic pseudo-random task."""
    task_type = TASK_TYPES[index % len(TASK_TYPES)]
    due_date = semester_start + timedelta(days=rng.randrange(0, 120))
    week_number = min(13, max(1, ((due_date - semester_start).days // 7) + 1))
    module_code = None if task_type == "personal" else rng.choice(_MODULE_CODES)
    due_time = rng.choice(_TIME_CHOICES)
    return Task(
        title=f"Stress task {index:05d}",
        task_type=task_type,
        module_code=module_code,
        due_date=due_date,
        due_time=due_time,
        week_number=week_number,
        notes="Generated by scripts/stress_db.py" if index % 11 == 0 else None,
        chat_id=_STRESS_CHAT_ID,
    )


def run_stress(task_count: int, query_count: int, mutation_count: int) -> None:
    """Populate a temporary DB, run read/write workloads, and print timings."""
    rng = random.Random(_RNG_SEED)
    semester_start = date.today()

    with TemporaryDirectory(prefix="taskbot-stress-") as tmp_dir:
        db.DB_PATH = Path(tmp_dir) / "tasks.db"
        db.init_db()

        for code in _MODULE_CODES:
            db.add_module(Module(code=code, name=f"{code} generated module"))

        tasks = [
            _generate_task(index, rng, semester_start)
            for index in range(task_count)
        ]
        started = time.perf_counter()
        inserted_ids = db.add_tasks(tasks)
        insert_seconds = time.perf_counter() - started

        query_timings: list[float] = []
        for _ in range(query_count):
            target = semester_start + timedelta(days=rng.randrange(0, 120))
            query_timings.append(
                _measure_ms(db.get_tasks_for_date, target, _STRESS_CHAT_ID)
            )
            query_timings.append(
                _measure_ms(
                    db.get_tasks_for_week,
                    rng.randrange(1, 14),
                    _STRESS_CHAT_ID,
                )
            )
            query_timings.append(
                _measure_ms(db.get_semester_deadlines, _STRESS_CHAT_ID)
            )

        mutation_timings: list[float] = []
        live_ids = inserted_ids.copy()
        for index in range(mutation_count):
            if not live_ids:
                break
            task_id = rng.choice(live_ids)
            if index % 3 == 0:
                mutation_timings.append(
                    _measure_ms(db.mark_complete, task_id, _STRESS_CHAT_ID)
                )
            elif index % 3 == 1:
                task = db.get_task(task_id, _STRESS_CHAT_ID)
                if task is not None:
                    task.notes = f"Updated during stress pass {index}"
                    mutation_timings.append(_measure_ms(db.update_task, task))
            else:
                mutation_timings.append(
                    _measure_ms(db.delete_task, task_id, _STRESS_CHAT_ID)
                )
                live_ids.remove(task_id)

        remaining = db.count_tasks()

        print(f"temporary_db={db.DB_PATH}")
        print(f"seed={_RNG_SEED}")
        print(f"tasks_inserted={task_count}")
        print(f"rows_remaining={remaining}")
        print(
            "insert_time="
            f"{insert_seconds:.3f}s ({task_count / insert_seconds:.0f} rows/s)"
        )
        print(
            "query_latency_ms="
            f"avg {statistics.fmean(query_timings):.3f}, "
            f"p95 {_p95(query_timings):.3f}, max {max(query_timings):.3f}"
        )
        print(
            "mutation_latency_ms="
            f"avg {statistics.fmean(mutation_timings):.3f}, "
            f"p95 {_p95(mutation_timings):.3f}, max {max(mutation_timings):.3f}"
        )


def main(argv: list[str] | None = None) -> int:
    """Parse CLI arguments and run the stress workload."""
    parser = argparse.ArgumentParser(
        description="Stress-test Task-Bot's SQLite data layer.",
    )
    parser.add_argument(
        "--tasks",
        type=int,
        default=3000,
        help="Number of generated tasks to insert.",
    )
    parser.add_argument(
        "--queries",
        type=int,
        default=1000,
        help="Number of read iterations; each iteration runs three query types.",
    )
    parser.add_argument(
        "--mutations",
        type=int,
        default=1000,
        help="Number of generated update/complete/delete operations.",
    )
    args = parser.parse_args(argv)

    if args.tasks <= 0 or args.queries <= 0 or args.mutations < 0:
        parser.error("--tasks and --queries must be positive; --mutations cannot be negative")

    run_stress(args.tasks, args.queries, args.mutations)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
